services:
  dagit:
    image: ${APP_IMAGE}
    ports:
      - "4000:3000"
    environment:
      - DAGSTER_HOME=/opt/app
      - PYTHONPATH=/opt/app
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - HF_TOKEN=${HF_TOKEN}
      - HUGGINGFACE_DATASET_REPO_ID=${HUGGINGFACE_DATASET_REPO_ID}
    volumes:
      - dagster-instance:/opt/dagster-instance
    command: dagit -h 0.0.0.0 -p 3000
    restart: unless-stopped

  dagster:
    image: ${APP_IMAGE}
    environment:
      - DAGSTER_HOME=/opt/app
      - PYTHONPATH=/opt/app
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - HF_TOKEN=${HF_TOKEN}
      - HUGGINGFACE_DATASET_REPO_ID=${HUGGINGFACE_DATASET_REPO_ID}
    volumes:
      - dagster-instance:/opt/dagster-instance
    command: dagster-daemon run
    restart: unless-stopped

volumes:
  dagster-instance:
